module.exports = [
  "Electronics",
  "Clothing",
  "Home",
  "Books",
  "Toys",
  "Beauty and Personal Care",
  "Sports and Outdoors",
  "Jewelry",
  "Health",
  "Automotive",
  "Pet Supplies",
  "Art and Craft Supplies",
  "Office Supplies",
  "Travel and Luggage",
  "Food and Beverages",
  "Other",
]
