import { z } from "zod"

export const clientEnvSchema = z.object({
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().min(1),
  NEXT_PUBLIC_CLOUDINARY_KEY: z.string().min(1),
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: z.string().min(1),
  NEXT_PUBLIC_CLOUDINARY_UPLOAD_URL: z.url(),
  NEXT_PUBLIC_CLOUDINARY_DESTROY_URL: z.url(),
})

export const clientEnv = clientEnvSchema.parse({
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  NEXT_PUBLIC_CLOUDINARY_KEY: process.env.NEXT_PUBLIC_CLOUDINARY_KEY,
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME:
    process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  NEXT_PUBLIC_CLOUDINARY_UPLOAD_URL:
    process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_URL,
  NEXT_PUBLIC_CLOUDINARY_DESTROY_URL:
    process.env.NEXT_PUBLIC_CLOUDINARY_DESTROY_URL,
})
